stages:
  - github-sync
  - build
  - test
  - package
  - prerelease
  - release

push_to_github:
  stage: github-sync
  variables:
    GIT_STRATEGY: none
  tags:
    - redshift
  script:
    - rm -rf ./*
    - rm -rf .git
    - git clone --mirror $CI_REPOSITORY_URL .
    - git remote add github $GITHUB_URL_AND_KEY
    - git config --global user.email "contact@duniter.org"
    - git config --global user.name "Duniter"
    # Job would fail if we don't remove refs about pull requests
    - bash -c "cat packed-refs | grep -v 'refs/pull' > packed-refs-new; echo 'Removed pull refs.'"
    - mv packed-refs-new packed-refs
    - bash -c "git push --force --mirror github 2>&1 | grep -v duniter-gitlab; echo $?"
  only:
    - nodes/typescript/duniter

.mvn_env: &mvn_env
  tags:
    - redshift
  before_script:
    - export NVM_DIR="$HOME/.nvm"
    - . "$NVM_DIR/nvm.sh"
  
build:
  <<: *mvn_env
  stage: build
  script:
    - yarn

test:
  <<: *mvn_env
  stage: test
  script:
    - yarn
    - yarn test

.build_releases: &build_releases
  stage: package
  allow_failure: false
  image: duniter/release-builder:v1.0.1
  tags:
    - redshift-duniter-builder
  when: manual
  artifacts:
    paths: &releases_artifacts
      - work/bin/

releases:test:
  <<: *build_releases
  script:
    - bash "release/arch/linux/build-lin.sh" "$(date +%Y%m%d).$(date +%H%M).$(date +%S)"
  artifacts:
    paths: *releases_artifacts
    expire_in: 4h
  except:
    - tags

releases:x64:
  <<: *build_releases
  script:
    - bash "release/arch/linux/build-lin.sh" "${CI_COMMIT_TAG#v}"
  artifacts:
    paths: *releases_artifacts
    expire_in: 2 weeks
  only:
    - tags

.release_jobs: &release_jobs
  image: tensorflow/tensorflow:latest-py3
  tags:
    - redshift-duniter-builder
  script:
    - python3 .gitlab/releaser.py
  only:
    - tags

prerelease:
  <<: *release_jobs
  stage: prerelease
  variables:
    RELEASE_BIN_DIR: work/bin/
    SOURCE_EXT: '["tar.gz", "zip"]'
    RELEASE_JOB: publish

publish:
  <<: *release_jobs
  stage: release
  variables:
    WIKI_RELEASE: Releases
  allow_failure: false
  when: manual
