stages:
  - github-sync
  - build
  - test
  - releases
  - releases-page

push_to_github:
  stage: github-sync
  variables:
    GIT_STRATEGY: none
  tags:
    - redshift
  script:
    - rm -rf ./*
    - rm -rf .git
    - git clone --mirror $CI_REPOSITORY_URL .
    - git remote add github $GITHUB_URL_AND_KEY
    - git config --global user.email "contact@duniter.org"
    - git config --global user.name "Duniter"
    # Job would fail if we don't remove refs about pull requests
    - bash -c "cat packed-refs | grep -v 'refs/pull' > packed-refs-new; echo 'Removed pull refs.'"
    - mv packed-refs-new packed-refs
    - bash -c "git push --force --mirror github 2>&1 | grep -v duniter-gitlab; echo $?"
  only:
    - nodes/typescript/duniter
        
build:
  stage: build
  tags:
    - redshift
  before_script:
    - export NVM_DIR="$HOME/.nvm"
    - . "$NVM_DIR/nvm.sh"
  script:
    - yarn

test:
  stage: test
  tags:
    - redshift
  before_script:
    - export NVM_DIR="$HOME/.nvm"
    - . "$NVM_DIR/nvm.sh"
  script:
    - yarn
    - yarn test

releases:test:
  stage: releases
  image: duniter/release-builder:v1.0.1
  tags:
    - redshift-duniter-builder
  variables:
    DAY: $(date +%Y%m%d)
    HOUR: $(date +%H%M)
    SEC: $(date +%S)
  script:
    - bash "release/arch/linux/build-lin.sh" "$(date +%Y%m%d).$(date +%H%M).$(date +%S)"
  artifacts:
    paths:
      - work/bin/
    expire_in: 8h
  when: manual
  except:
    - tags

releases:
  stage: releases
  image: duniter/release-builder:v1.0.1
  tags:
    - redshift-duniter-builder
  script:
    - bash "release/arch/linux/build-lin.sh" "${CI_COMMIT_TAG#v}"
  artifacts:
    paths:
      - work/bin/duniter-desktop-${CI_COMMIT_TAG}-linux-x64.deb
      - work/bin/duniter-desktop-${CI_COMMIT_TAG}-linux-x64.tar.gz
      - work/bin/duniter-server-${CI_COMMIT_TAG}-linux-x64.deb
    expire_in: 8h
  when: manual
  only:
  - tags
  - master
    
releases-message:
  stage: releases-page
  image: tensorflow/tensorflow:latest-py3
  tags:
    - redshift-duniter-builder
  variables:
    JOB_ARTIFACTS: 'releases'
    EXPECTED_ARTIFACTS: '["work/bin/duniter-desktop-${CI_COMMIT_TAG}-linux-x64.deb","work/bin/duniter-desktop-${CI_COMMIT_TAG}-linux-x64.tar.gz","work/bin/duniter-server-${CI_COMMIT_TAG}-linux-x64.deb"]'
  script:
    - python3 .gitlab/releaser.py
  when: manual
  only:
  - tags
  - master
