environment:
  matrix:
    - nodejs_version: "8.9.2"
      ADDON_VERSION: "48"

platform:
  - x64

install:
  - echo %ADDON_VERSION%
  - ps: Update-NodeJsInstallation $env:nodejs_version $env:platform
  - node -v
  - npm install -g npm
  - npm install -g nw-gyp node-pre-gyp
  - npm install

build: off
