[package]
authors = ["elois <elois@duniter.org>"]
description = "Duniter launcher."
edition = "2018"
keywords = ["duniter", "launcher"]
license = "AGPL-3.0"
name = "duniter-launcher"
repository = "https://git.duniter.org/nodes/typescript/duniter"
version = "1.8.1"

[[bin]]
bench = false
path = "rust-bins/duniter-launcher/src/main.rs"
name = "duniter"

[dependencies]
anyhow = "1.0.32"
ctrlc = "3.1.6"
daemonize-me = "0.3.1"
dirs = "3.0.1"
log = "0.4.11"
logwatcher = "0.1.1"
nix = "0.17.0"
structopt = "0.3.18"

[dev-dependencies]
rusty-hook = "0.11.2"

[workspace]
members = [
    "neon/native",
    "rust-bins/xtask",
    "rust-libs/dubp-wot",
    "rust-libs/duniter-dbs",
    "rust-libs/tools/kv_typed",
    "rust-libs/tools/kv_typed_code_gen"
]

[patch.crates-io]
#dubp-common = { path = "../dubp-rs-libs/common" }
#dubp-documents  = { path = "../dubp-rs-libs/documents" }
#dubp-documents-parser = { path = "../dubp-rs-libs/documents-parser" }
#dubp-wallet  = { path = "../dubp-rs-libs/wallet" }
#leveldb_minimal = { path = "../../../../rust/leveldb_minimal" }
