[workspace]
members = [
    "neon/native",
    "rust-libs/dubp-wot"
]

[patch.crates-io]
#dubp-common = { path = "../dubp-rs-libs/common" }
#dubp-documents  = { path = "../dubp-rs-libs/documents" }
#dubp-documents-parser = { path = "../dubp-rs-libs/documents-parser" }
#dubp-wallet  = { path = "../dubp-rs-libs/wallet" }
