[package]
name = "duniteroxyde"
version = "1.8.1"
authors = ["librelois <elois@ifee.fr>"]
license = "AGPL-3.0"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "duniteroxyde"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.4.0"

[dependencies]
bincode = "1.2.1"
bs58 = "0.3.0"
dubp = { version = "0.32.3" }
dubp-wot = { path = "../../rust-libs/dubp-wot" }
duniter-server = { path = "../../rust-libs/duniter-server" }
flate2 = "1.0.16"
flexi_logger = { version = "=0.16.0", default-features = false, features = ["compress"] }
flume = "0.9.1"
log = "0.4.11"
neon = "0.4.0"
neon-serde = "0.4.0"
once_cell = "1.4.1"
serde = { version = "1.0.105", features = ["derive"] }

[dev-dependencies]
unwrap = "1.2.1"
