[package]
name = "duniteroxyde"
version = "0.3.0"
authors = ["librelois <elois@ifee.fr>"]
license = "AGPL-3.0"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "duniteroxyde"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.4.0"

[dependencies]
bincode = "1.2.1"
bs58 = "0.3.0"
dubp-common = { version = "0.25.0", features = ["crypto_scrypt"] }
dubp-documents = { version = "0.25.0" }
dubp-documents-parser = { version = "0.25.0" }
dubp-wallet = { version = "0.25.0" }
dubp-wot = { path = "../../rust-libs/dubp-wot" }
flate2 = "1.0.16"
flexi_logger = { version = "=0.16.0", default-features = false, features = ["compress"] }
log = "0.4.11"
neon = "0.4.0"
neon-serde = "0.4.0"

[dev-dependencies]
unwrap = "1.2.1"
